// src/ui/texxy_ui_prelude.h
#pragma once

#include "encoding.h"
#include "filedialog.h"
#include "fontDialog.h"
#include "loading.h"
#include "messagebox.h"
#include "pref.h"
#include "session.h"
#include "singleton.h"
#include "svgicons.h"
#include "textedit/textedit.h"
#include "texxywindow.h"
#include "ui_texxywindow.h"
#include "ui/menubartitle.h"
#include "ui/tabbar.h"
#include "ui/tabpage.h"
#include "warningbar.h"

#include <algorithm>

#include <QAction>
#include <QActionGroup>
#include <QApplication>
#include <QClipboard>
#include <QDateTime>
#include <QDBusConnection>
#include <QDBusMessage>
#include <QDesktopServices>
#include <QDialog>
#include <QDir>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFont>
#include <QFontMetrics>
#include <QGridLayout>
#include <QGuiApplication>
#include <QIcon>
#include <QKeySequence>
#include <QLabel>
#include <QList>
#include <QListWidget>
#include <QListWidgetItem>
#include <QLocale>
#include <QMenu>
#include <QMessageBox>
#include <QMimeData>
#include <QMimeDatabase>
#include <QPlainTextDocumentLayout>
#include <QPlainTextEdit>
#include <QPointer>
#include <QProcess>
#include <QPushButton>
#include <QRegularExpression>
#include <QScreen>
#include <QScrollBar>
#include <QShortcut>
#include <QSize>
#include <QStandardPaths>
#include <QStringDecoder>
#include <QTextBlock>
#include <QTextCursor>
#include <QTextDocument>
#include <QTextEdit>
#include <QTextStream>
#include <QTimer>
#include <QToolButton>
#include <QToolTip>
#include <QUrl>
#include <QWidgetAction>
#include <QWindow>

#ifdef HAS_X11
#include "x11.h"
#endif
